package com.github.noonmaru.regions

enum class Permission {
    OWNERSHIP,
    ADMINISTRATION,
    ENTRANCE,
    EXIT,
    INTERACTION,
    ENTITY_ATTACK,
    PLAYER_ATTACK,
    PROJECTILE_LAUNCH,
    BLOCK_BREAK,
    BLOCK_PLACE,
    BLOCK_IGNITING,
    BUCKET_FILL,
    BUCKET_EMPTY,
    HANGING_BREAK,
    HANGING_PLACE,
    DROP_ITEM,
    PICKUP_ITEM
}